import { initSeo } from "remix-seo";
export const { getSeo, getSeoMeta, getSeoLinks } = initSeo({
	// Pass any SEO defaults for your site here.
	// If individual routes do not provide their own meta and link tags,
	// the tags generated by the defaults will be used.
	title: "Annie Sexton",
	titleTemplate: "%s | Annie Sexton",
	description: "A blog about software engineering, product develoment, and tech-shenanigans.",
});